### ISSUE TITLE
Negative standard deviations for non-normal distributions.

### ISSUE THREAD

**Issue by mayermelhem** [pystra/pystra#19]
Pystra Team, 

I ported over to `pystra` for some project work which previously ran `pyre` but now was getting `nan` results for the reliability index running FORM, whereas `pyre` still continued to provide the usual results. 

Upon further investigation, I noticed the culprit is a negative quantity (say `S`). When adding `S` to `StochasticModel` as per the approach shown in the tutorial with a known bias and coefficient of variation, I'm guessing the standard deviation is defined as a negative quantity. `pyre` seems to address this for `S` as a non-normal distribution (Gumbel has been explored), however `pystra` does not. This issue is not observed if `S` is a normal (Gaussian) random variable.    

I attach a MWE for you to explore the issue. 

```python

import pystra

def lsf(R,S):
    return R - (2 + S) 

def ra_simple(S_nom):
  
    # Set the limit state
    limit_state = pr.LimitState(lsf)

    # The model
    stochastic_model = pr.StochasticModel()

    # Capacity variables
    r_dist = pr.Normal("R", *1.4*1.05 * np.array([1.0, 0.1]))
    stochastic_model.addVariable(r_dist)

    # Loading variables
    stochastic_model.addVariable(pr.Gumbel("S", *S_nom* 1.00 * np.array([1.0, 0.1]))) 
    
    # some options
    options = pr.AnalysisOptions()
    options.e1 = 1e-4
    options.e2 = 1e-6
    
    form = pr.Form(
        analysis_options=options,
        stochastic_model=stochastic_model,
        limit_state=limit_state,
    )
    beta = form.getBeta()
    pf = form.getFailure()
    alpha_2 = (form.getAlpha())**2
    
    form.showDetailedOutput()

    return beta, pf, alpha_2

s = -1 # negative nominal value
ra_simple(s)

```

Keep up the good work!

**Comment by ccaprani** [comment]
Thanks @mayermelhem, this is good behaviour from `pystra`. As you note, the arguments `-1 * np.array([1.0, 0.1])` actually passes a negative standard deviation, which is impossible, and so `nan` is the right response.

Compare:

```python
S_nom = -1
pr.Gumbel("S", *S_nom* 1.00 * np.array([1.0, 0.1])).plot()
```
which outputs an empty chart, to
```python
S_nom = 1
pr.Gumbel("S", *S_nom* 1.00 * np.array([1.0, 0.1])).plot()
```
![image](https://user-images.githubusercontent.com/31228546/139514756-7be9042f-87a1-40fa-bffa-ce81721c859d.png)

A user warning of a negative standard deviation would be useful.

**Comment by ccaprani** [comment]
Closed with https://github.com/pystra/pystra/commit/ce80b2e7e39e12f078729bf0db567146eed4b310.
