### ISSUE TITLE
`fsolve` in Weibull Distribution 

### ISSUE THREAD

**Issue by mayermelhem** [pystra/pystra#24]
As per [scipy documentation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.fsolve.html), `scipy.optimize.fsolve` does not have a `disp` kwarg. Consequently, when instantiating a `Weibull()` variable given a mean and standard deviation, an error is raised. 

MWE

```python
import pystra as pr

pr.Weibull( 'd', 40, 0.2*40 )

TypeError: fsolve() got an unexpected keyword argument 'disp'
```

**Comment by ccaprani** [comment]
Fantastic - this pointed to an underlying problem. This is now fixed with https://github.com/pystra/pystra/commit/85d559bb5b166ee460af1256c132d82a521cb8af.
