### ISSUE TITLE
FORM printing e1, e2 values

### ISSUE THREAD

**Issue by AndrewCWay** [pystra/pystra#25]
Hi Profs

Since updating from PyRe to Pystra - When performing a FORM analysis ( pyr.form.Form() ), even when all print options are turned off, three lines of "e1 = 1.000000e+00 , e2 = 1.811878e-01" are printed out to the screen as part of the FORM analysis. Is there perhaps any way to suppress this behaviour?

Thanks.
Andrew

**Comment by ccaprani** [comment]
Thanks for highlighting that @AndrewCWay - I've fixed that now in https://github.com/pystra/pystra/commit/3c3a0cafb44b3fc05ad452827c543e1d9a3acd8a, so just `pip install git+git://github.com/pystra/pystra.git` again to update.
