### ISSUE TITLE
About Pystra

### ISSUE THREAD

**Issue by Jungle-13** [pystra/pystra#26]
Hello,Sir.I am a student in the School of Civil Engineering, Harbin Institute of Technology, China. My name is Wang Zhangong. I am very grateful to you for this package, it is very useful, thank you for your contribution. However, I would like to ask when you could finish the reference document(http://pystra.github.io/pystra/README.html), and also, whether you can improve the package to calculate the load or resistance of the partial factors. Or, do you have the recommended technical means or code to calculate the itemized coefficient, would you like to tell me about this ,thank you!
Best wishes!

**Comment by ccaprani** [comment]
Hi @Jungle-13 ! Thanks for raising this and your acknowledgement! 

The pystra documentation is not intended as a textbook on reliability methods, but just a guide with some background to the package. If you're not sufficiently familiar with the theory, check out some key references such as:

- Reliability of Structures - Nowak & Collins
- Structural Reliability Analysis & Prediction - Melchers & Beck
- Structural Reliability - Lemaire
- Structural Reliability Theory and Its Applications - Thoft-Christensen & Baker
- Structural Reliability - Madsen, Krenk & Lind

Code calibration is currently outside of the scope of the package, but pystra can be used to help with code calibration. If you or someone else does wish to contribute a code calibration module to pystra, it would be welcomed! Some references for this are:

- Probability, Reliability and Statistical Methods in Engineering Design - Haldar & Mahadevan
- Reliability-based Structural Design - Choi, Grandhi & Canfield
- Notes in Structural Reliability Theory And Risk Analysis - Sorenson
- Structural Reliability Methods - Ditlevsen & Madsen

**Comment by Jungle-13** [comment]
Thank you,sir!Thank you for your reply!
I mean pystra's examples are relatively small, would you like to add more examples for others to learn?
Best wishes!
Wangzhangong




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pystra/pystra"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 上午8:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pystra/pystra] About Pystra (Issue #26)





 
Hi @Jungle-13 ! Thanks for raising this and your acknowledgement!
 
The pystra documentation is not intended as a textbook on reliability methods, but just a guide with some background to the package. If you're not sufficiently familiar with the theory, check out some key references such as:
  
Reliability of Structures - Nowak &amp; Collins
 
Structural Reliability Analysis &amp; Prediction - Melchers &amp; Beck
 
Structural Reliability - Lemaire
 
Structural Reliability Theory and Its Applications - Thoft-Christensen &amp; Baker
 
Structural Reliability - Madsen, Krenk &amp; Lind
  
Code calibration is currently outside of the scope of the package, but pystra can be used to help with code calibration. If you or someone else does wish to contribute a code calibration module to pystra, it would be welcomed! Some references for this are:
  
Probability, Reliability and Statistical Methods in Engineering Design - Haldar &amp; Mahadevan
 
Reliability-based Structural Design - Choi, Grandhi &amp; Canfield
 
Notes in Structural Reliability Theory And Risk Analysis - Sorenson
 
Structural Reliability Methods - Ditlevsen &amp; Madsen
  
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ccaprani** [comment]
@Jungle-13 the current set of examples cover all of the capabilities of pystra so far. They are not exhaustive with respect to structural reliability of course, because the potential limit state functions and other ways of using it are infinite. But if you think there is another example that will help clarify the use of the package, you could prepare it and submit it as a PR - if you need any help doing this, just ask!

**Comment by Jungle-13** [comment]
Thank you ,Sir.&nbsp;I am very lucky and happy to ask you the questions.&nbsp;
Thanks for your answer!
Best wishes!
Wang zhangong




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pystra/pystra"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 下午5:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [pystra/pystra] About Pystra (Issue #26)





 
@Jungle-13 the current set of examples cover all of the capabilities of pystra so far. They are not exhaustive with respect to structural reliability of course, because the potential limit state functions and other ways of using it are infinite. But if you think there is another example that will help clarify the use of the package, you could prepare it and submit it as a PR - if you need any help doing this, just ask!
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
