### ISSUE TITLE
pystra into fe analysis

### ISSUE THREAD

**Issue by luizcarlosveras** [pystra/pystra#27]
Hello everyone!!

I'm trying to use Pystra in my FEA code, but a problem came up. For simplicity, suppose a truss problem where the limit state function is in terms of nodal displacement, how can I handle the arrays of the limit state function arguments (area and load, in this example) since the FEA code expected floats?

Thank you all!

**Comment by ccaprani** [comment]
In your limit state function, loop over the length of the input parameters and call-by-call to the FEA assemble the vector of outcomes to return to pystra.

**Comment by luizcarlosveras** [comment]
Works fine! Thank you very much!
