### ISSUE TITLE
Gradient of limit state function

### ISSUE THREAD

**Issue by mhscott** [pystra/pystra#30]
Nice work @ccaprani with pystra! I chatted with @hackl about this briefly at ICASP 2019, but it would be nice to have a gradient_limit_state object for the reliability analyses. Instead of relying on finite differences within pystra, we can call an external function, i.e., OpenSees, for DDM-based gradients. For moderate size models, the time savings should be quite large.

```
# LSF
g = 0.1-ops.nodeDisp(2,1)
# Grad LSF
dgdh[0] = -ops.sensNodeDisp(2,1,1)
dgdh[1] = -ops.sensNodeDisp(2,1,2)
# etc.
```

I may be oversimplifying things as I'm a little rusty on reliability and have never been razor sharp. I think a Jacobian has to get in there too, but I'm pretty sure that can be handled within pystra.

**Comment by ccaprani** [comment]
@mhscott thank you so much for prompting this. It had been on the ToDo list for a long time!

v1.1 now has DDM enabled. An example using just closed-form expressions is in the docs [here](http://pystra.github.io/pystra/notebooks/ex_ddm.html). It would be great to have an example in OpenSeesPy, but I was hesitant to add it here as it would then need to be a docs build requirement.

There were a few other things I got done as well that had been on the radar; although a minor version release there are a few breaking changes in there.

Let me know how you go - I'm eager to see how it goes for you! Thanks again.
