### ISSUE TITLE
Problem with adding conditional case in limit state function

### ISSUE THREAD

**Issue by zooxs** [pystra/pystra#52]
Hi, thanks for your hard work. I just come a problem with this condition in limit state function
```{python}
def example_limitstatefunction(X1, X2):
    if X1 > 5:
        return X1 - X2
    else:
        return X2/2 - X1
```
this is the error log:
![image](https://user-images.githubusercontent.com/65235797/219527683-6a60dea8-c9e3-4e78-be03-11a5765cc82f.png)

Its really help me if there a way to implement conditional case in function.
Thanks.

**Comment by ccaprani** [comment]
Your limit state function is called in a vectorized format. That is, a vector of X1 and X2 will be submitted to it. The error is saying that you cannot compare a whole vector of numbers to a scalar.

A poor solution would be to loop over the length of the vectors passed in, calculating the value for g in each loop, using whatever conditional you want.

A better solution is to use `np.where` to find the indices where one condition applies. For example:

```python
indx = np.where(X1>5)
g =  X2/2 - X1
g[indx] = X1[indx] - X2[indx]
return g
```

But note that this cannot be called passing scalars.

There is a further problem with this LSF - it has a discontinuity at 5. This will probably cause problems with FORM. LSFs are typically continuous.

**Comment by zooxs** [comment]
Thanks for your answer. Is there any solution for discontinuity LSF for evaluate FORM? Like evaluate its based on separate domain?

**Comment by ccaprani** [comment]
It seems an unusual problem requirement: maybe there's a way that your problem can be formulated so that the LSF is continuous?

Treating the domains separately is a good idea too; then treat it as a series system.

**Comment by zooxs** [comment]
Indeed. That formula i took from [researches](https://www.sciencedirect.com/science/article/abs/pii/S0308016116301855?via%3Dihub) about reliability analysis in pipeline. Regardless, there still some thing that i don't understand about your code which is your way to compute partial derivative of LSF. If you don't mind, could you give some references how to do that? I still use manual way to determine its partial derivative. Best regard, thanks.

**Comment by ccaprani** [comment]
Differentiation of the limit state function is explained [in the documentation](https://pystra.github.io/pystra/gen/pystra.model.LimitState.html#pystra.model.LimitState).
