### ISSUE TITLE
Analysis not yet run

### ISSUE THREAD

**Issue by aaronsxzhao** [pystra/pystra#53]
Python Version: `3.11`
pystra Version: `1.2.2`

I came across an unexpected issue while running **Example:  gev_example.py**.

> ValueError: Analysis not yet run

I just copied and pasted the code and did not change anything. Is it possible for me to solve it?

Thanks

**Comment by ccaprani** [comment]
Thanks for this. It just needed a `form.run()` command to be added on Line 33: https://github.com/pystra/pystra/commit/f3915546c3bfa63a5ecad287cd681d590e61e740

This became necessary since v1.1.0: https://github.com/pystra/pystra/releases/tag/v1.1.0
