### ISSUE TITLE
The way to determine relationship between random variabel and reliability index

### ISSUE THREAD

**Issue by zooxs** [pystra/pystra#55]
Currently i'm writing my final project related to reliability analysis in corroded pipeline. I want to determine relationship between defect depth of corrosion as random variable with reliability index as [this paper](https://www.sciencedirect.com/science/article/abs/pii/0308016196000099) does. Is it possible doing this task with Pystra?

Also this is the desired graph that i want to get.

![beta_depth](https://github.com/pystra/pystra/assets/65235797/0ca36614-85c0-44ba-bcc0-c0f06f0831a3)

Thank you in advances.

**Comment by ccaprani** [comment]
The paper provides a closed-form FOSM formulation; you don't need PySTRA for this. If you're not sure about reliability analysis, read some of the [references](http://pystra.github.io/pystra/references.html) and get some assistance from your supervisor.

Closing as not a software issue.
